### ISSUE TITLE
Most things not working

### ISSUE THREAD

**Issue by Psyden57** [rayhea/GTAVMACROS#1] opened 2023-03-02 14:37 UTC
A lot of things seem to not be working, been trying the phone macros, interaction menu macros, and the hacking macros, but they don't seem to work.

I've been thinking it might be the OCR not working at all, since it always seems to just do a single keypress if anything, and then nothing
Yes i have checked i have the correct resolution, windowed mode (borderless) and all

Is there a way to check if the OCR is working? and fix it?

**Comment by rayhea** [comment] 2023-03-08 14:50
Can you first check if Screen Type is just windowed and not windowed borderless and if it is 

Problem might be with OCR but it should have affected only interaction menu macros since it is only used for getting the title and selected label of interaction menu.

Also can you tell me in detail what happens after you press F5 to equip armor, F7 to call mechanic and also ~ for Script Menu to see if single press and double press work or not.

And if Script Menu is showing then look for Menu in Other tab (used for debugging) and check if after pressing m for interaction menu does it change from Menu None to Menu IntMenu just to check if pixel detection for interaction menu is working or not also make sure that Script Menu gui is not on top of interaction menu. You can also try with up arrow key to bring out phone and check.

mean while i will try to add something to check OCR in Other tab or just using tooltip.

**Comment by rayhea** [comment] 2023-03-08 15:21
i think the problem is windowed mode being borderless
Can you first try just Screen Type windowed (not borderless) and then try the above

**Comment by Psyden57** [comment] 2023-03-08 17:12
So i had it on windowed borderless, not regular windowed since it'd not be exactly 1360x768 in windowed with the task bar and all, but i did try on regular windowed and it wouldn't work either

sadly i can't check stuff right now since i'm back on my old monitor (1280x1024), the other one broke

**Comment by rayhea** [comment] 2023-03-09 14:08
That's the thing all the settings needs to be exactly the same as given in necessary changes and even after that some or whole feature might not work. 

Best thing to do is to check whether script detects that menu opening/closing from Menu in Other Tab.

You can also tailor the script according to your own settings but you had to change tons of pixel/image coordinates of where things might be on screen and also need to take those images again in temp/img as .bmp but its too much even for me.

but still you don't have worry there are tons of macros which faster and don't rely on pixel/image detection i hope you find 
something that works for you.

**Comment by rayhea** [comment] 2023-03-09 14:14
That's the thing all the settings needs to be exactly the same as given in necessary changes and even after that some or whole feature might not work.

Best thing to do is to check whether the script detects opening/closing of the menu's from Menu in Other Tab.

You can also tailor the script according to your own settings but you had to change tons of pixel/image coordinates of where things might be on screen and also need to take those images as shown in temp/img as .bmp but its too much even for me.

but still you don't have to worry there are tons of macros which are way faster and don't rely on pixel/image detection and I hope you find something that works for you.

**Closed as completed** 2023-03-11 14:43 UTC
